<?php

namespace Database\Seeders;

use App\Models\StandardClause;
use Illuminate\Database\Seeder;

/**
 * Taksonomi klausul/pasal 7 standar (182 klausul) — struktur & judul klausul
 * diambil dari susunan resmi tiap standar (ISO 9001:2015, ISO 14001:2015,
 * ISO 45001:2018, ISO 27001:2022 Annex A terpilih, ISO 22301:2019,
 * ISO 37001:2016, SMK3/PP 50:2012), BUKAN dikarang — supaya baris
 * Compliance Matrix mencerminkan struktur standar yang sesungguhnya.
 * ISO 31000 & ISO 15489 sengaja belum diisi (belum ada taksonomi klausul
 * terverifikasi untuk keduanya) — matriks akan menampilkan 0 klausul untuk
 * dua standar itu sampai ditambahkan, bukan angka yang dikarang.
 *
 * updateOrCreate per (standard_code, code) supaya aman dijalankan berulang
 * di produksi tanpa menggandakan baris.
 */
class StandardClauseSeeder extends Seeder
{
    public function run(): void
    {
        foreach (self::CLAUSES as $standardCode => $clauses) {
            foreach ($clauses as $i => [$code, $title]) {
                StandardClause::updateOrCreate(
                    ['standard_code' => $standardCode, 'code' => $code],
                    ['title' => $title, 'sort_order' => $i],
                );
            }
        }
    }

    /** @var array<string, list<array{0: string, 1: string}>> */
    private const CLAUSES = [
        'ISO9001' => [
            ['4.1', 'Konteks Organisasi'],
            ['4.2', 'Kebutuhan & Ekspektasi Pihak Berkepentingan'],
            ['4.3', 'Penetapan Ruang Lingkup SMM'],
            ['4.4', 'SMM dan Proses-prosesnya'],
            ['5.1', 'Kepemimpinan dan Komitmen'],
            ['5.2', 'Kebijakan Mutu'],
            ['5.3', 'Peran, Tanggung Jawab & Wewenang Organisasi'],
            ['6.1', 'Tindakan Menangani Risiko & Peluang'],
            ['6.2', 'Sasaran Mutu dan Perencanaan Pencapaiannya'],
            ['6.3', 'Perencanaan Perubahan'],
            ['7.1', 'Sumber Daya'],
            ['7.2', 'Kompetensi'],
            ['7.3', 'Kepedulian'],
            ['7.4', 'Komunikasi'],
            ['7.5', 'Informasi Terdokumentasi'],
            ['8.1', 'Perencanaan & Pengendalian Operasional'],
            ['8.2', 'Persyaratan Produk dan Jasa'],
            ['8.3', 'Desain dan Pengembangan'],
            ['8.4', 'Pengendalian Proses/Produk/Jasa dari Pihak Eksternal'],
            ['8.5', 'Produksi dan Penyediaan Jasa'],
            ['8.6', 'Pelepasan Produk dan Jasa'],
            ['8.7', 'Pengendalian Output Tidak Sesuai'],
            ['9.1', 'Pemantauan, Pengukuran, Analisis & Evaluasi'],
            ['9.2', 'Audit Internal'],
            ['9.3', 'Tinjauan Manajemen'],
            ['10.1', 'Umum (Peningkatan)'],
            ['10.2', 'Ketidaksesuaian dan Tindakan Korektif'],
            ['10.3', 'Peningkatan Berkelanjutan'],
        ],
        'ISO14001' => [
            ['4.1', 'Konteks Organisasi'],
            ['4.2', 'Kebutuhan & Ekspektasi Pihak Berkepentingan'],
            ['4.3', 'Ruang Lingkup SML'],
            ['4.4', 'Sistem Manajemen Lingkungan'],
            ['5.1', 'Kepemimpinan dan Komitmen'],
            ['5.2', 'Kebijakan Lingkungan'],
            ['5.3', 'Peran, Tanggung Jawab & Wewenang Organisasi'],
            ['6.1.1', 'Umum (Tindakan Risiko & Peluang)'],
            ['6.1.2', 'Aspek Lingkungan'],
            ['6.1.3', 'Kewajiban Kepatuhan'],
            ['6.1.4', 'Perencanaan Tindakan'],
            ['6.2', 'Sasaran Lingkungan dan Perencanaan Pencapaiannya'],
            ['7.1', 'Sumber Daya'],
            ['7.2', 'Kompetensi'],
            ['7.3', 'Kepedulian'],
            ['7.4', 'Komunikasi'],
            ['7.5', 'Informasi Terdokumentasi'],
            ['8.1', 'Perencanaan & Pengendalian Operasional'],
            ['8.2', 'Kesiapan & Tanggap Darurat'],
            ['9.1', 'Pemantauan, Pengukuran, Analisis & Evaluasi'],
            ['9.2', 'Audit Internal'],
            ['9.3', 'Tinjauan Manajemen'],
            ['10.1', 'Umum (Peningkatan)'],
            ['10.2', 'Ketidaksesuaian dan Tindakan Korektif'],
            ['10.3', 'Peningkatan Berkelanjutan'],
        ],
        'ISO45001' => [
            ['4.1', 'Konteks Organisasi'],
            ['4.2', 'Kebutuhan & Ekspektasi Pekerja & Pihak Berkepentingan'],
            ['4.3', 'Ruang Lingkup SM K3'],
            ['4.4', 'Sistem Manajemen K3'],
            ['5.1', 'Kepemimpinan dan Komitmen'],
            ['5.2', 'Kebijakan K3'],
            ['5.3', 'Peran, Tanggung Jawab & Wewenang Organisasi'],
            ['5.4', 'Konsultasi dan Partisipasi Pekerja'],
            ['6.1.1', 'Umum (Tindakan Risiko & Peluang)'],
            ['6.1.2', 'Identifikasi Bahaya & Penilaian Risiko K3'],
            ['6.1.3', 'Penentuan Persyaratan Hukum & Lainnya'],
            ['6.1.4', 'Perencanaan Tindakan'],
            ['6.2', 'Sasaran K3 dan Perencanaan Pencapaiannya'],
            ['7.1', 'Sumber Daya'],
            ['7.2', 'Kompetensi'],
            ['7.3', 'Kepedulian'],
            ['7.4', 'Komunikasi K3'],
            ['7.5', 'Informasi Terdokumentasi'],
            ['8.1.1', 'Umum (Perencanaan & Pengendalian Operasional)'],
            ['8.1.2', 'Eliminasi Bahaya & Penurunan Risiko K3'],
            ['8.1.3', 'Manajemen Perubahan'],
            ['8.1.4', 'Pengadaan (Procurement)'],
            ['8.2', 'Kesiapan & Tanggap Darurat'],
            ['9.1', 'Pemantauan, Pengukuran, Analisis & Evaluasi Kinerja'],
            ['9.2', 'Audit Internal'],
            ['9.3', 'Tinjauan Manajemen'],
            ['10.1', 'Umum (Peningkatan)'],
            ['10.2', 'Investigasi Insiden'],
            ['10.3', 'Peningkatan Berkelanjutan'],
        ],
        'SMK3' => [
            ['I', 'Penetapan Kebijakan K3'],
            ['II', 'Perencanaan K3'],
            ['III', 'Pelaksanaan Rencana K3'],
            ['IV', 'Pemantauan dan Evaluasi Kinerja K3'],
            ['V', 'Peninjauan dan Peningkatan Kinerja SMK3'],
        ],
        'ISO27001' => [
            ['4.1', 'Konteks Organisasi'],
            ['4.2', 'Kebutuhan & Ekspektasi Pihak Berkepentingan'],
            ['4.3', 'Ruang Lingkup SMKI'],
            ['4.4', 'Sistem Manajemen Keamanan Informasi'],
            ['5.1', 'Kepemimpinan dan Komitmen'],
            ['5.2', 'Kebijakan'],
            ['5.3', 'Peran, Tanggung Jawab & Wewenang Organisasi'],
            ['6.1.1', 'Umum (Tindakan Risiko & Peluang)'],
            ['6.1.2', 'Penilaian Risiko Keamanan Informasi'],
            ['6.1.3', 'Penanganan Risiko Keamanan Informasi'],
            ['6.2', 'Sasaran Keamanan Informasi'],
            ['6.3', 'Perencanaan Perubahan'],
            ['7.1', 'Sumber Daya'],
            ['7.2', 'Kompetensi'],
            ['7.3', 'Kepedulian'],
            ['7.4', 'Komunikasi'],
            ['7.5', 'Informasi Terdokumentasi'],
            ['8.1', 'Perencanaan & Pengendalian Operasional'],
            ['8.2', 'Penilaian Risiko Keamanan Informasi (Operasional)'],
            ['8.3', 'Penanganan Risiko Keamanan Informasi (Operasional)'],
            ['9.1', 'Pemantauan, Pengukuran, Analisis & Evaluasi'],
            ['9.2', 'Audit Internal'],
            ['9.3', 'Tinjauan Manajemen'],
            ['10.1', 'Peningkatan Berkelanjutan'],
            ['10.2', 'Ketidaksesuaian dan Tindakan Korektif'],
            ['A.5.1', 'Kebijakan Keamanan Informasi'],
            ['A.5.9', 'Inventarisasi Informasi & Aset Terkait'],
            ['A.5.15', 'Kontrol Akses'],
            ['A.5.23', 'Keamanan Informasi untuk Layanan Cloud'],
            ['A.6.3', 'Kepedulian, Edukasi & Pelatihan Keamanan Informasi'],
            ['A.7.1', 'Perimeter Keamanan Fisik'],
            ['A.8.1', 'Perangkat Endpoint Pengguna'],
            ['A.8.9', 'Manajemen Konfigurasi'],
            ['A.8.16', 'Aktivitas Pemantauan'],
            ['A.8.24', 'Penggunaan Kriptografi'],
        ],
        'ISO22301' => [
            ['4.1', 'Konteks Organisasi'],
            ['4.2', 'Kebutuhan & Ekspektasi Pihak Berkepentingan'],
            ['4.3', 'Ruang Lingkup SMKB'],
            ['4.4', 'Sistem Manajemen Keberlangsungan Bisnis'],
            ['5.1', 'Kepemimpinan dan Komitmen'],
            ['5.2', 'Kebijakan'],
            ['5.3', 'Peran, Tanggung Jawab & Wewenang Organisasi'],
            ['6.1', 'Tindakan Menangani Risiko & Peluang'],
            ['6.2', 'Sasaran Keberlangsungan Bisnis'],
            ['6.3', 'Perencanaan Perubahan'],
            ['7.1', 'Sumber Daya'],
            ['7.2', 'Kompetensi'],
            ['7.3', 'Kepedulian'],
            ['7.4', 'Komunikasi'],
            ['7.5', 'Informasi Terdokumentasi'],
            ['8.1', 'Perencanaan & Pengendalian Operasional'],
            ['8.2', 'Business Impact Analysis'],
            ['8.3', 'Strategi & Solusi Keberlangsungan Bisnis'],
            ['8.4', 'Rencana & Prosedur Keberlangsungan Bisnis'],
            ['8.5', 'Program Latihan (Exercise)'],
            ['8.6', 'Evaluasi Dokumentasi & Kapabilitas Keberlangsungan Bisnis'],
            ['9.1', 'Pemantauan, Pengukuran, Analisis & Evaluasi'],
            ['9.2', 'Audit Internal'],
            ['9.3', 'Tinjauan Manajemen'],
            ['10.1', 'Peningkatan Berkelanjutan'],
            ['10.2', 'Ketidaksesuaian dan Tindakan Korektif'],
        ],
        'ISO37001' => [
            ['4.1', 'Konteks Organisasi'],
            ['4.2', 'Kebutuhan & Ekspektasi Pihak Berkepentingan'],
            ['4.3', 'Ruang Lingkup SMAP'],
            ['4.4', 'Sistem Manajemen Anti Penyuapan'],
            ['4.5', 'Penilaian Risiko Penyuapan'],
            ['5.1', 'Kepemimpinan dan Komitmen'],
            ['5.2', 'Kebijakan Anti Penyuapan'],
            ['5.3', 'Peran, Tanggung Jawab & Wewenang Organisasi'],
            ['5.4', 'Badan Pengelola (Governing Body)'],
            ['5.5', 'Manajemen Puncak'],
            ['6.1', 'Tindakan Menangani Risiko & Peluang'],
            ['6.2', 'Sasaran Anti Penyuapan'],
            ['7.1', 'Sumber Daya'],
            ['7.2', 'Kompetensi'],
            ['7.3', 'Pelatihan'],
            ['7.4', 'Kepedulian'],
            ['7.5', 'Komunikasi'],
            ['7.6', 'Informasi Terdokumentasi'],
            ['8.1', 'Perencanaan & Pengendalian Operasional'],
            ['8.2', 'Uji Kelayakan (Due Diligence)'],
            ['8.3', 'Kontrol Keuangan'],
            ['8.4', 'Kontrol Non-Keuangan'],
            ['8.5', 'Penerapan Kontrol Anti Penyuapan pada Mitra & Rekanan Bisnis'],
            ['8.6', 'Komitmen Anti Penyuapan'],
            ['8.7', 'Hadiah, Jamuan, Donasi & Manfaat Serupa'],
            ['8.8', 'Penanganan Ketidakcukupan Kontrol Anti Penyuapan'],
            ['8.9', 'Pelaporan Kekhawatiran (Whistleblowing)'],
            ['8.10', 'Investigasi & Penanganan Penyuapan'],
            ['9.1', 'Pemantauan, Pengukuran, Analisis & Evaluasi'],
            ['9.2', 'Audit Internal'],
            ['9.3', 'Tinjauan Manajemen'],
            ['9.4', 'Tinjauan oleh Fungsi Kepatuhan Anti Penyuapan'],
            ['10.1', 'Ketidaksesuaian dan Tindakan Korektif'],
            ['10.2', 'Peningkatan Berkelanjutan'],
        ],
    ];
}
